heat_template_version: 2014-10-16

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: swap_config}

  swap_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        set -eux
        if [[ -z $(cat /proc/swaps | grep -v Filename) ]]; then
          sudo dd if=/dev/zero of=/swapfile count=4k bs=1M
          sudo mkswap /swapfile
          sudo chmod 0600 /swapfile
          sudo swapon /swapfile
          cat /proc/swaps
        fi

outputs:
  OS::stack_id:
    value: {get_resource: userdata}

