compute_memory: 7168
control_memory: 8192
objectstorage_memory: 7168
default_vcpu: 1
undercloud_vcpu: 2
undercloud_memory: 8192
node_count: 5
overcloud_nodes:
  - name: control_0
    flavor: control
    virtualbmc_port: 6230
  - name: control_1
    flavor: control
    virtualbmc_port: 6231
  - name: control_2
    flavor: control
    virtualbmc_port: 6232
  - name: compute_0
    flavor: compute
    virtualbmc_port: 6233
  - name: objectstorage_0
    flavor: objectstorage
    virtualbmc_port: 6234

topology: >-
  --control-scale 3
  --compute-scale 1
  --object-storage-scale 1

extra_args: >-
  --libvirt-type qemu
  -e /usr/share/openstack-tripleo-heat-templates/environments/puppet-pacemaker.yaml

run_tempest: false
enable_pacemaker: true

